name: Build & Test

on:
  push:
    branches: [ "ft/ci" ]
  pull_request:
    branches: [ "ft/ci" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup JDK11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: adopt
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git emacs-nox curl
    - name: Install cask
      run: |
        mkdir -p $HOME/.local/bin
        git clone https://github.com/cask/cask.git /tmp/cask
        cd /tmp/cask
        make install
    - name: Download plantuml.jar
      run: ./bin/download-plantuml.sh
    - name: Build & Test
      run: |
        export PATH=$PATH:$HOME/.local/bin
        make
